### ISSUE TITLE
Bug report: libmpdclient v2.20 Crash. 

### ISSUE THREAD

**Issue by zj3t** [MusicPlayerDaemon/libmpdclient#96]
## Describe the bug
Vulnerability in libmpdclient  v2.20.
When a malicious MP3 is played, the libmpdclient  is crashed.

A vulnerability has been discovered in Automotive Grade Linux (AGL) using libmpdclient  v2.20.

MP3 files were moved and played in the environment.
After that, it was confirmed that libmpdclient(v2.20)  Crashed.

![image](https://user-images.githubusercontent.com/35731091/210069714-1b0cc438-eea5-46ec-bdf3-b6904b99c804.png)

Checking the log, mpd_status_get_elapsed_ms: Assertion `status != NULL' faile.
That part appears to be the cause of the crash.

## Crash File
I will attach different files that cause the crash.

[exp.zip](https://github.com/MusicPlayerDaemon/libmpdclient/files/10324643/exp.zip)

## ETC
I first reported this problem to AGL.
-> https://jira.automotivelinux.org/browse/SPEC-4661

However, I think it's probably a problem with your client library (libmpdclient), which is open source.

Please check and reply.

**Comment by MaxKellermann** [comment]
No, you're wrong here as well. There is indeed such a function in libmpdclient, but this is a runtime debug check alerting that the libmpdclient API was used with an illegal argument. The bug is in your application which calls libmpdclient, not in libmpdclient.
Note that you compiled libmpdclient in debug mode (`b_ndebug=false`). For production use, you should disable debugging (i.e. `b_ndebug=true`).
